# Vaya al siguiente enlace y use el boton "Run workflow" para generar este pipeline
# https://github.com/bancodebogota/bbog-dig-do-testing-pipeline/actions/workflows/generate_pipeline_requirements.yml

# Documentacion en Confluence:
# https://bancodebogotaconfluence.atlassian.net/wiki/spaces/LABDIGITAL/pages/3643670908/Requirements